=== mkaramuk/tohum/metadata.schema.json
{
  "$id": "https://raw.githubusercontent.com/mkaramuk/tohum/main/metadata.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "tohumrc",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "description": "Version of the seed in SemVer format"
    },
    "name": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "authors": {
      "type": "array",
      "description": "List of authors",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "website": {
            "type": "string"
          }
        }
      },
      "required": ["name"]
    },
    "variables": {
      "type": "object",
      "description": "Templating variables",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["string", "number"]
          },
          "default": {},
          "required": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          }
        },
        "required": ["type", "description"],
        "allOf": [
          {
            "if": {
              "properties": {
                "type": { "const": "number" }
              }
            },
            "then": {
              "properties": {
                "default": { "type": "number" }
              }
            },
            "else": {
              "properties": {
                "default": { "type": "string" }
              }
            }
          }
        ]
      }
    }
  },
  "required": ["version", "name", "authors"]
}

=== mkaramuk/tohum/templates/node/cli/ts_1.1.0/.tohum/metadata.json
{
  "$schema": "https://raw.githubusercontent.com/mkaramuk/tohum/main/metadata.schema.json",
  "version": "1.1.0",
  "name": "ts",
  "description": "TypeScript/Node.js CLI application with eslint + Prettier + tsup setup",
  "authors": [
    {
      "name": "Muhammed Karamuk",
      "url": "https://mkaramuk.dev"
    }
  ],
  "variables": {
    "version": {
      "type": "string",
      "default": "1.0.0",
      "description": "package.json version field"
    },
    "description": {
      "type": "string",
      "default": "TypeScript project",
      "description": "package.json description field"
    },
    "license": {
      "type": "string",
      "default": "ISC",
      "description": "package.json license field"
    }
  }
}
